version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "deok"
      POSTGRES_PASSWORD: "power"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/:/var/lib/postgresql/data
